rootDocument: /deeply/abc/def/ghi
hoistHeadings: true
headerButtons:
  - title: Sponsor
    icon: SiGithubsponsors
    link: https://github.com
    target: _blank
  - title: GitHub
    icon: FaGithub
    link: https://github.com
styles:
  primary: steelblue
noSidebar: false