name: Docs
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v3
      - run: yarn install
      - run: npm install --os=linux --cpu=x64 sharp
      - run: yarn run build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/out
      - uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/out
